### ISSUE TITLE
my comfyui manager can't use this node

### ISSUE THREAD

**Issue by Lagrebanana** [chrisgoringe/cg-mixed-casting#13]
I download this node, but can't use this node.It's a version question?

**Comment by chrisgoringe** [comment]
Hmm. I've sort of retired this node on favour of a better approach :)

**Comment by Lagrebanana** [comment]
So what can I quantity my model 😥

**Comment by chrisgoringe** [comment]
Try the thing I'm working on to replace it:

https://github.com/chrisgoringe/mixed-gguf-converter

Post questions on that repository if you have trouble!
